// <auto-generated />
namespace EfRepPatTest.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCultures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCultures));
        
        string IMigrationMetadata.Id
        {
            get { return "201307121313454_AddCultures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
