// <auto-generated />
namespace EfRepPatTest.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTranslations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTranslations));
        
        string IMigrationMetadata.Id
        {
            get { return "201307150649143_Add-Translations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
