// <auto-generated />
namespace EfRepPatTest.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTranslationsToSpaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTranslationsToSpaces));
        
        string IMigrationMetadata.Id
        {
            get { return "201307170830072_AddTranslationsToSpaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
